TOP_DIR = ..

BASE = rom

SRC = ./tb_rom.sv ./stimulator.sv ./rom_backend.sv \
	  ./rom_front.sv ./rom_wr.sv ./rom_rd.sv \
	  ../common/clk_rst.sv ../common/dff.sv ../common/tilelink.sv

include ../makefile.common
