TOP_DIR = ../..

BASE = rom

SRC = ./tb_rom.sv ./rom_stim.sv ./rom_backend.sv \
	  ./rom_front.sv ./rom_wr.sv ./rom_rd.sv \
	  ${SRC_DIR}/clk_rst.sv ${SRC_DIR}/dff.sv ${SRC_DIR}/tilelink.sv

include ../makefile.common
