# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cloud/gitLocal/msoc/fpga/uart/uart.srcs/sources_1/ip/uartlite/uartlite.xci
# IP: The module: 'uartlite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cloud/gitLocal/msoc/fpga/uart/uart.srcs/sources_1/ip/uartlite/uartlite.xci
# IP: The module: 'uartlite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cloud/gitLocal/msoc/fpga/uart/uart.gen/sources_1/ip/uartlite/uartlite.xdc
# XDC: The top module name and the constraint reference have the same name: 'uartlite'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
