BASE = middle

SRC = tb_${BASE}.sv ../stimulator.sv ${SRC_DIR}/r_rom_frontend.sv \
	${SRC_DIR}/tilelink.sv ${SRC_DIR}/dff.sv ${SRC_DIR}/clk_rst.sv \
	${IP_DIR}/ip_fifo.sv

include ../../makefile.common
